# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
 [push]
jobs:
  build:
    container: openjdk:13
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install maven
      run: apt install -y --no-install-recommends maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
